### ISSUE TITLE
windows 平台使用 chiflix/electron3.0.0-beta.3 will get Error: net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by lycbel2** [chiflix/electron#1]
貌似需要建立ssl 连接的地方无法建立连接，可能是electron里的问题，ps：使用官方的3.0.0-beta.3 没有这个问题。

代码： @import url("https://use.typekit.net/ybq0nrw.css");
会导致： ybq0nrw.css:1 Failed to load resource: net::ERR_CONNECTION_RESET ||
                                         Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR

electron updater 的error：
[14:01:43:0318] [info] update error at rejection: Error: net::ERR_SSL_PROTOCOL_ERROR
      at CancellationToken.createPromise (C:\develop\new\splayerx\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
      at ElectronHttpExecutor.doApiRequest (C:\develop\new\splayerx\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
      at ElectronHttpExecutor.request (C:\develop\new\splayerx\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
      at GitHubProvider.httpRequest (C:\develop\new\splayerx\node_modules\electron-updater\src\providers\Provider.ts:29:26)
      at C:\develop\new\splayerx\node_modules\electron-updater\src\providers\GitHubProvider.ts:38:41
      at Generator.next (<anonymous>)

**Comment by ymmuse** [comment]
已修复。删掉node_modules/@chiflix/electron 目录重新安装一下。后续还有问题再开issue
